# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jharrison\Documents\GitHub\BundleTool\misc_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_misc_Dialog(object):
    def setupUi(self, misc_Dialog):
        misc_Dialog.setObjectName("misc_Dialog")
        misc_Dialog.resize(442, 500)
        self.buttonBox = QtWidgets.QDialogButtonBox(misc_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 450, 221, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gaskets_label = QtWidgets.QLabel(misc_Dialog)
        self.gaskets_label.setGeometry(QtCore.QRect(30, 160, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gaskets_label.setFont(font)
        self.gaskets_label.setObjectName("gaskets_label")
        self.shop_bundle_label = QtWidgets.QLabel(misc_Dialog)
        self.shop_bundle_label.setGeometry(QtCore.QRect(30, 360, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.shop_bundle_label.setFont(font)
        self.shop_bundle_label.setObjectName("shop_bundle_label")
        self.hex_label = QtWidgets.QLabel(misc_Dialog)
        self.hex_label.setGeometry(QtCore.QRect(30, 280, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hex_label.setFont(font)
        self.hex_label.setObjectName("hex_label")
        self.studs_label = QtWidgets.QLabel(misc_Dialog)
        self.studs_label.setGeometry(QtCore.QRect(30, 240, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.studs_label.setFont(font)
        self.studs_label.setObjectName("studs_label")
        self.gaskets2_label = QtWidgets.QLabel(misc_Dialog)
        self.gaskets2_label.setGeometry(QtCore.QRect(30, 200, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gaskets2_label.setFont(font)
        self.gaskets2_label.setObjectName("gaskets2_label")
        self.redraw_label = QtWidgets.QLabel(misc_Dialog)
        self.redraw_label.setGeometry(QtCore.QRect(30, 320, 47, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.redraw_label.setFont(font)
        self.redraw_label.setObjectName("redraw_label")
        self.tubesheet_label = QtWidgets.QLabel(misc_Dialog)
        self.tubesheet_label.setGeometry(QtCore.QRect(16, 40, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tubesheet_label.setFont(font)
        self.tubesheet_label.setObjectName("tubesheet_label")
        self.baffles_label = QtWidgets.QLabel(misc_Dialog)
        self.baffles_label.setGeometry(QtCore.QRect(30, 120, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.baffles_label.setFont(font)
        self.baffles_label.setObjectName("baffles_label")
        self.tubes_label = QtWidgets.QLabel(misc_Dialog)
        self.tubes_label.setGeometry(QtCore.QRect(30, 80, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tubes_label.setFont(font)
        self.tubes_label.setObjectName("tubes_label")
        self.part_number_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit.setGeometry(QtCore.QRect(130, 40, 113, 20))
        self.part_number_lineEdit.setObjectName("part_number_lineEdit")
        self.part_number_lineEdit_2 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_2.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.part_number_lineEdit_2.setObjectName("part_number_lineEdit_2")
        self.part_number_lineEdit_3 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_3.setGeometry(QtCore.QRect(130, 120, 113, 20))
        self.part_number_lineEdit_3.setObjectName("part_number_lineEdit_3")
        self.part_number_lineEdit_4 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_4.setGeometry(QtCore.QRect(130, 160, 113, 20))
        self.part_number_lineEdit_4.setObjectName("part_number_lineEdit_4")
        self.part_number_lineEdit_5 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_5.setGeometry(QtCore.QRect(130, 200, 113, 20))
        self.part_number_lineEdit_5.setObjectName("part_number_lineEdit_5")
        self.part_number_lineEdit_6 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_6.setGeometry(QtCore.QRect(130, 240, 113, 20))
        self.part_number_lineEdit_6.setObjectName("part_number_lineEdit_6")
        self.part_number_lineEdit_7 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_7.setGeometry(QtCore.QRect(130, 280, 113, 20))
        self.part_number_lineEdit_7.setObjectName("part_number_lineEdit_7")
        self.part_number_lineEdit_8 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_8.setGeometry(QtCore.QRect(130, 320, 113, 20))
        self.part_number_lineEdit_8.setObjectName("part_number_lineEdit_8")
        self.part_number_lineEdit_9 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_9.setGeometry(QtCore.QRect(130, 360, 113, 20))
        self.part_number_lineEdit_9.setObjectName("part_number_lineEdit_9")
        self.parts_number_label = QtWidgets.QLabel(misc_Dialog)
        self.parts_number_label.setGeometry(QtCore.QRect(140, 10, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parts_number_label.setFont(font)
        self.parts_number_label.setObjectName("parts_number_label")
        self.spinBox = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox.setGeometry(QtCore.QRect(250, 40, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_2.setGeometry(QtCore.QRect(250, 80, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_3.setGeometry(QtCore.QRect(250, 120, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_4.setGeometry(QtCore.QRect(250, 160, 42, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_5.setGeometry(QtCore.QRect(250, 200, 42, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_6.setGeometry(QtCore.QRect(250, 240, 42, 22))
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_7.setGeometry(QtCore.QRect(250, 280, 42, 22))
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_8 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_8.setGeometry(QtCore.QRect(250, 320, 42, 22))
        self.spinBox_8.setObjectName("spinBox_8")
        self.spinBox_9 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_9.setGeometry(QtCore.QRect(250, 360, 42, 22))
        self.spinBox_9.setObjectName("spinBox_9")
        self.tubesheet_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.tubesheet_unit_cost_lineEdit.setGeometry(QtCore.QRect(310, 40, 113, 20))
        self.tubesheet_unit_cost_lineEdit.setObjectName("tubesheet_unit_cost_lineEdit")
        self.tubes_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.tubes_unit_cost_lineEdit.setGeometry(QtCore.QRect(310, 80, 113, 20))
        self.tubes_unit_cost_lineEdit.setObjectName("tubes_unit_cost_lineEdit")
        self.baffles_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.baffles_unit_cost_lineEdit.setGeometry(QtCore.QRect(310, 120, 113, 20))
        self.baffles_unit_cost_lineEdit.setObjectName("baffles_unit_cost_lineEdit")
        self.gaskets_unit_cost_lineEdit_1 = QtWidgets.QLineEdit(misc_Dialog)
        self.gaskets_unit_cost_lineEdit_1.setGeometry(QtCore.QRect(310, 160, 113, 20))
        self.gaskets_unit_cost_lineEdit_1.setObjectName("gaskets_unit_cost_lineEdit_1")
        self.gaskets_unit_cost_lineEdit_2 = QtWidgets.QLineEdit(misc_Dialog)
        self.gaskets_unit_cost_lineEdit_2.setGeometry(QtCore.QRect(310, 200, 113, 20))
        self.gaskets_unit_cost_lineEdit_2.setObjectName("gaskets_unit_cost_lineEdit_2")
        self.studs_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.studs_unit_cost_lineEdit.setGeometry(QtCore.QRect(310, 240, 113, 20))
        self.studs_unit_cost_lineEdit.setObjectName("studs_unit_cost_lineEdit")
        self.hex_nuts_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.hex_nuts_unit_cost_lineEdit.setGeometry(QtCore.QRect(310, 280, 113, 20))
        self.hex_nuts_unit_cost_lineEdit.setObjectName("hex_nuts_unit_cost_lineEdit")
        self.redraw_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.redraw_cost_lineEdit.setGeometry(QtCore.QRect(310, 320, 113, 20))
        self.redraw_cost_lineEdit.setObjectName("redraw_cost_lineEdit")
        self.shop_hours_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.shop_hours_cost_lineEdit.setGeometry(QtCore.QRect(310, 360, 113, 20))
        self.shop_hours_cost_lineEdit.setObjectName("shop_hours_cost_lineEdit")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(misc_Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(240, 410, 61, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.markup_label = QtWidgets.QLabel(misc_Dialog)
        self.markup_label.setGeometry(QtCore.QRect(240, 390, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.markup_label.setFont(font)
        self.markup_label.setObjectName("markup_label")
        self.label = QtWidgets.QLabel(misc_Dialog)
        self.label.setGeometry(QtCore.QRect(330, 410, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.per_item_label = QtWidgets.QLabel(misc_Dialog)
        self.per_item_label.setGeometry(QtCore.QRect(320, 10, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.per_item_label.setFont(font)
        self.per_item_label.setObjectName("per_item_label")
        self.total_cost_label = QtWidgets.QLabel(misc_Dialog)
        self.total_cost_label.setGeometry(QtCore.QRect(330, 390, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_cost_label.setFont(font)
        self.total_cost_label.setObjectName("total_cost_label")

        self.retranslateUi(misc_Dialog)
        self.buttonBox.accepted.connect(misc_Dialog.accept)
        self.buttonBox.rejected.connect(misc_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(misc_Dialog)
        misc_Dialog.setTabOrder(self.part_number_lineEdit, self.spinBox)
        misc_Dialog.setTabOrder(self.spinBox, self.tubesheet_unit_cost_lineEdit)
        misc_Dialog.setTabOrder(self.tubesheet_unit_cost_lineEdit, self.part_number_lineEdit_2)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_2, self.spinBox_2)
        misc_Dialog.setTabOrder(self.spinBox_2, self.tubes_unit_cost_lineEdit)
        misc_Dialog.setTabOrder(self.tubes_unit_cost_lineEdit, self.part_number_lineEdit_3)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_3, self.spinBox_3)
        misc_Dialog.setTabOrder(self.spinBox_3, self.baffles_unit_cost_lineEdit)
        misc_Dialog.setTabOrder(self.baffles_unit_cost_lineEdit, self.part_number_lineEdit_4)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_4, self.spinBox_4)
        misc_Dialog.setTabOrder(self.spinBox_4, self.gaskets_unit_cost_lineEdit_1)
        misc_Dialog.setTabOrder(self.gaskets_unit_cost_lineEdit_1, self.part_number_lineEdit_5)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_5, self.spinBox_5)
        misc_Dialog.setTabOrder(self.spinBox_5, self.gaskets_unit_cost_lineEdit_2)
        misc_Dialog.setTabOrder(self.gaskets_unit_cost_lineEdit_2, self.part_number_lineEdit_6)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_6, self.spinBox_6)
        misc_Dialog.setTabOrder(self.spinBox_6, self.studs_unit_cost_lineEdit)
        misc_Dialog.setTabOrder(self.studs_unit_cost_lineEdit, self.part_number_lineEdit_7)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_7, self.spinBox_7)
        misc_Dialog.setTabOrder(self.spinBox_7, self.hex_nuts_unit_cost_lineEdit)
        misc_Dialog.setTabOrder(self.hex_nuts_unit_cost_lineEdit, self.part_number_lineEdit_8)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_8, self.spinBox_8)
        misc_Dialog.setTabOrder(self.spinBox_8, self.redraw_cost_lineEdit)
        misc_Dialog.setTabOrder(self.redraw_cost_lineEdit, self.part_number_lineEdit_9)
        misc_Dialog.setTabOrder(self.part_number_lineEdit_9, self.spinBox_9)
        misc_Dialog.setTabOrder(self.spinBox_9, self.shop_hours_cost_lineEdit)
        misc_Dialog.setTabOrder(self.shop_hours_cost_lineEdit, self.doubleSpinBox)

    def retranslateUi(self, misc_Dialog):
        _translate = QtCore.QCoreApplication.translate
        misc_Dialog.setWindowTitle(_translate("misc_Dialog", "Dialog"))
        self.gaskets_label.setText(_translate("misc_Dialog", "Gaskets"))
        self.shop_bundle_label.setText(_translate("misc_Dialog", "Shop Hours"))
        self.hex_label.setText(_translate("misc_Dialog", "Hex Nuts"))
        self.studs_label.setText(_translate("misc_Dialog", "Studs"))
        self.gaskets2_label.setText(_translate("misc_Dialog", "Gaskets"))
        self.redraw_label.setText(_translate("misc_Dialog", "Redraw"))
        self.tubesheet_label.setText(_translate("misc_Dialog", "Tubesheet"))
        self.baffles_label.setText(_translate("misc_Dialog", "Baffles"))
        self.tubes_label.setText(_translate("misc_Dialog", "Tubes"))
        self.parts_number_label.setText(_translate("misc_Dialog", "Parts Numbers"))
        self.markup_label.setText(_translate("misc_Dialog", "Mark Up"))
        self.per_item_label.setText(_translate("misc_Dialog", "Cost Per Item"))
        self.total_cost_label.setText(_translate("misc_Dialog", "Total Cost:"))

