# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jharrison\Documents\GitHub\BundleTool\misc_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_misc_Dialog(object):
    def setupUi(self, misc_Dialog):
        misc_Dialog.setObjectName("misc_Dialog")
        misc_Dialog.resize(439, 674)
        misc_Dialog.setMinimumSize(QtCore.QSize(439, 674))
        self.hex_nuts_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.hex_nuts_unit_cost_lineEdit.setGeometry(QtCore.QRect(300, 280, 113, 20))
        self.hex_nuts_unit_cost_lineEdit.setObjectName("hex_nuts_unit_cost_lineEdit")
        self.redraw_label = QtWidgets.QLabel(misc_Dialog)
        self.redraw_label.setGeometry(QtCore.QRect(20, 370, 47, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.redraw_label.setFont(font)
        self.redraw_label.setObjectName("redraw_label")
        self.caclulated_list_price_label = QtWidgets.QLabel(misc_Dialog)
        self.caclulated_list_price_label.setGeometry(QtCore.QRect(310, 610, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.caclulated_list_price_label.setFont(font)
        self.caclulated_list_price_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caclulated_list_price_label.setObjectName("caclulated_list_price_label")
        self.parts_number_label = QtWidgets.QLabel(misc_Dialog)
        self.parts_number_label.setGeometry(QtCore.QRect(130, 10, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parts_number_label.setFont(font)
        self.parts_number_label.setObjectName("parts_number_label")
        self.part_number_lineEdit_5 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_5.setGeometry(QtCore.QRect(120, 200, 113, 20))
        self.part_number_lineEdit_5.setObjectName("part_number_lineEdit_5")
        self.markup_SpinBox_2 = QtWidgets.QDoubleSpinBox(misc_Dialog)
        self.markup_SpinBox_2.setGeometry(QtCore.QRect(240, 600, 61, 22))
        self.markup_SpinBox_2.setSingleStep(0.05)
        self.markup_SpinBox_2.setObjectName("markup_SpinBox_2")
        self.studs_label = QtWidgets.QLabel(misc_Dialog)
        self.studs_label.setGeometry(QtCore.QRect(20, 240, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.studs_label.setFont(font)
        self.studs_label.setObjectName("studs_label")
        self.part_number_lineEdit_3 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_3.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.part_number_lineEdit_3.setObjectName("part_number_lineEdit_3")
        self.spinBox_7 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_7.setGeometry(QtCore.QRect(240, 280, 42, 22))
        self.spinBox_7.setObjectName("spinBox_7")
        self.baffles_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.baffles_unit_cost_lineEdit.setGeometry(QtCore.QRect(300, 120, 113, 20))
        self.baffles_unit_cost_lineEdit.setObjectName("baffles_unit_cost_lineEdit")
        self.part_number_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.part_number_lineEdit.setObjectName("part_number_lineEdit")
        self.spinBox = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox.setGeometry(QtCore.QRect(240, 40, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.total_cost_label = QtWidgets.QLabel(misc_Dialog)
        self.total_cost_label.setGeometry(QtCore.QRect(310, 450, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_cost_label.setFont(font)
        self.total_cost_label.setObjectName("total_cost_label")
        self.rep_cost_label = QtWidgets.QLabel(misc_Dialog)
        self.rep_cost_label.setGeometry(QtCore.QRect(310, 550, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rep_cost_label.setFont(font)
        self.rep_cost_label.setObjectName("rep_cost_label")
        self.spinBox_6 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_6.setGeometry(QtCore.QRect(240, 240, 42, 22))
        self.spinBox_6.setObjectName("spinBox_6")
        self.gaskets2_label = QtWidgets.QLabel(misc_Dialog)
        self.gaskets2_label.setGeometry(QtCore.QRect(20, 200, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gaskets2_label.setFont(font)
        self.gaskets2_label.setObjectName("gaskets2_label")
        self.spinBox_3 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_3.setGeometry(QtCore.QRect(240, 120, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.part_number_lineEdit_7 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_7.setGeometry(QtCore.QRect(120, 280, 113, 20))
        self.part_number_lineEdit_7.setObjectName("part_number_lineEdit_7")
        self.spinBox_5 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_5.setGeometry(QtCore.QRect(240, 200, 42, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.tubesheet_label = QtWidgets.QLabel(misc_Dialog)
        self.tubesheet_label.setGeometry(QtCore.QRect(6, 40, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tubesheet_label.setFont(font)
        self.tubesheet_label.setObjectName("tubesheet_label")
        self.studs_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.studs_unit_cost_lineEdit.setGeometry(QtCore.QRect(300, 240, 113, 20))
        self.studs_unit_cost_lineEdit.setObjectName("studs_unit_cost_lineEdit")
        self.markup_label = QtWidgets.QLabel(misc_Dialog)
        self.markup_label.setGeometry(QtCore.QRect(240, 500, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.markup_label.setFont(font)
        self.markup_label.setObjectName("markup_label")
        self.hex_label = QtWidgets.QLabel(misc_Dialog)
        self.hex_label.setGeometry(QtCore.QRect(20, 280, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hex_label.setFont(font)
        self.hex_label.setObjectName("hex_label")
        self.part_number_lineEdit_4 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_4.setGeometry(QtCore.QRect(120, 160, 113, 20))
        self.part_number_lineEdit_4.setObjectName("part_number_lineEdit_4")
        self.calculated_rep_cost_label = QtWidgets.QLabel(misc_Dialog)
        self.calculated_rep_cost_label.setGeometry(QtCore.QRect(310, 570, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calculated_rep_cost_label.setFont(font)
        self.calculated_rep_cost_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calculated_rep_cost_label.setObjectName("calculated_rep_cost_label")
        self.spinBox_4 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_4.setGeometry(QtCore.QRect(240, 160, 42, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.markup_SpinBox = QtWidgets.QDoubleSpinBox(misc_Dialog)
        self.markup_SpinBox.setGeometry(QtCore.QRect(240, 520, 61, 22))
        self.markup_SpinBox.setSingleStep(0.25)
        self.markup_SpinBox.setObjectName("markup_SpinBox")
        self.part_number_lineEdit_6 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_6.setGeometry(QtCore.QRect(120, 240, 113, 20))
        self.part_number_lineEdit_6.setObjectName("part_number_lineEdit_6")
        self.tubesheet_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.tubesheet_unit_cost_lineEdit.setGeometry(QtCore.QRect(300, 40, 113, 20))
        self.tubesheet_unit_cost_lineEdit.setObjectName("tubesheet_unit_cost_lineEdit")
        self.spinBox_2 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_2.setGeometry(QtCore.QRect(240, 80, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.materials_cost_label = QtWidgets.QLabel(misc_Dialog)
        self.materials_cost_label.setGeometry(QtCore.QRect(310, 310, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.materials_cost_label.setFont(font)
        self.materials_cost_label.setObjectName("materials_cost_label")
        self.tubes_label = QtWidgets.QLabel(misc_Dialog)
        self.tubes_label.setGeometry(QtCore.QRect(20, 80, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tubes_label.setFont(font)
        self.tubes_label.setObjectName("tubes_label")
        self.gaskets_unit_cost_lineEdit_2 = QtWidgets.QLineEdit(misc_Dialog)
        self.gaskets_unit_cost_lineEdit_2.setGeometry(QtCore.QRect(300, 200, 113, 20))
        self.gaskets_unit_cost_lineEdit_2.setObjectName("gaskets_unit_cost_lineEdit_2")
        self.redraw_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.redraw_cost_lineEdit.setGeometry(QtCore.QRect(300, 370, 113, 20))
        self.redraw_cost_lineEdit.setObjectName("redraw_cost_lineEdit")
        self.gaskets_unit_cost_lineEdit_1 = QtWidgets.QLineEdit(misc_Dialog)
        self.gaskets_unit_cost_lineEdit_1.setGeometry(QtCore.QRect(300, 160, 113, 20))
        self.gaskets_unit_cost_lineEdit_1.setObjectName("gaskets_unit_cost_lineEdit_1")
        self.pushButton = QtWidgets.QPushButton(misc_Dialog)
        self.pushButton.setGeometry(QtCore.QRect(340, 640, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.per_item_label = QtWidgets.QLabel(misc_Dialog)
        self.per_item_label.setGeometry(QtCore.QRect(310, 10, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.per_item_label.setFont(font)
        self.per_item_label.setObjectName("per_item_label")
        self.calculated_materials_label = QtWidgets.QLabel(misc_Dialog)
        self.calculated_materials_label.setGeometry(QtCore.QRect(310, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calculated_materials_label.setFont(font)
        self.calculated_materials_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calculated_materials_label.setObjectName("calculated_materials_label")
        self.calculated_total_label = QtWidgets.QLabel(misc_Dialog)
        self.calculated_total_label.setGeometry(QtCore.QRect(310, 470, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calculated_total_label.setFont(font)
        self.calculated_total_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calculated_total_label.setObjectName("calculated_total_label")
        self.shop_hours_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.shop_hours_cost_lineEdit.setGeometry(QtCore.QRect(300, 410, 113, 20))
        self.shop_hours_cost_lineEdit.setObjectName("shop_hours_cost_lineEdit")
        self.list_price_label = QtWidgets.QLabel(misc_Dialog)
        self.list_price_label.setGeometry(QtCore.QRect(310, 590, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_price_label.setFont(font)
        self.list_price_label.setObjectName("list_price_label")
        self.markup_label_2 = QtWidgets.QLabel(misc_Dialog)
        self.markup_label_2.setGeometry(QtCore.QRect(240, 580, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.markup_label_2.setFont(font)
        self.markup_label_2.setObjectName("markup_label_2")
        self.tubes_unit_cost_lineEdit = QtWidgets.QLineEdit(misc_Dialog)
        self.tubes_unit_cost_lineEdit.setGeometry(QtCore.QRect(300, 80, 113, 20))
        self.tubes_unit_cost_lineEdit.setObjectName("tubes_unit_cost_lineEdit")
        self.part_number_lineEdit_2 = QtWidgets.QLineEdit(misc_Dialog)
        self.part_number_lineEdit_2.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.part_number_lineEdit_2.setObjectName("part_number_lineEdit_2")
        self.shop_bundle_label = QtWidgets.QLabel(misc_Dialog)
        self.shop_bundle_label.setGeometry(QtCore.QRect(20, 410, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.shop_bundle_label.setFont(font)
        self.shop_bundle_label.setObjectName("shop_bundle_label")
        self.gaskets_label = QtWidgets.QLabel(misc_Dialog)
        self.gaskets_label.setGeometry(QtCore.QRect(20, 160, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gaskets_label.setFont(font)
        self.gaskets_label.setObjectName("gaskets_label")
        self.spinBox_9 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_9.setGeometry(QtCore.QRect(240, 410, 42, 22))
        self.spinBox_9.setObjectName("spinBox_9")
        self.baffles_label = QtWidgets.QLabel(misc_Dialog)
        self.baffles_label.setGeometry(QtCore.QRect(20, 120, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.baffles_label.setFont(font)
        self.baffles_label.setObjectName("baffles_label")
        self.spinBox_8 = QtWidgets.QSpinBox(misc_Dialog)
        self.spinBox_8.setGeometry(QtCore.QRect(240, 370, 42, 22))
        self.spinBox_8.setObjectName("spinBox_8")

        self.retranslateUi(misc_Dialog)
        QtCore.QMetaObject.connectSlotsByName(misc_Dialog)

    def retranslateUi(self, misc_Dialog):
        _translate = QtCore.QCoreApplication.translate
        misc_Dialog.setWindowTitle(_translate("misc_Dialog", "Dialog"))
        self.hex_nuts_unit_cost_lineEdit.setText(_translate("misc_Dialog", "0"))
        self.redraw_label.setText(_translate("misc_Dialog", "Redraw"))
        self.caclulated_list_price_label.setText(_translate("misc_Dialog", "0"))
        self.parts_number_label.setText(_translate("misc_Dialog", "Parts Numbers"))
        self.studs_label.setText(_translate("misc_Dialog", "Studs"))
        self.baffles_unit_cost_lineEdit.setText(_translate("misc_Dialog", "0"))
        self.total_cost_label.setText(_translate("misc_Dialog", "Total Cost:"))
        self.rep_cost_label.setText(_translate("misc_Dialog", "Rep Cost:"))
        self.gaskets2_label.setText(_translate("misc_Dialog", "Gaskets"))
        self.tubesheet_label.setText(_translate("misc_Dialog", "Tubesheet"))
        self.studs_unit_cost_lineEdit.setText(_translate("misc_Dialog", "0"))
        self.markup_label.setText(_translate("misc_Dialog", "Mark Up"))
        self.hex_label.setText(_translate("misc_Dialog", "Hex Nuts"))
        self.calculated_rep_cost_label.setText(_translate("misc_Dialog", "0"))
        self.tubesheet_unit_cost_lineEdit.setText(_translate("misc_Dialog", "0"))
        self.materials_cost_label.setText(_translate("misc_Dialog", "Materials Cost:"))
        self.tubes_label.setText(_translate("misc_Dialog", "Tubes"))
        self.gaskets_unit_cost_lineEdit_2.setText(_translate("misc_Dialog", "0"))
        self.redraw_cost_lineEdit.setText(_translate("misc_Dialog", "0"))
        self.gaskets_unit_cost_lineEdit_1.setText(_translate("misc_Dialog", "0"))
        self.pushButton.setText(_translate("misc_Dialog", "Calculate"))
        self.per_item_label.setText(_translate("misc_Dialog", "Cost Per Item"))
        self.calculated_materials_label.setText(_translate("misc_Dialog", "0"))
        self.calculated_total_label.setText(_translate("misc_Dialog", "0"))
        self.shop_hours_cost_lineEdit.setText(_translate("misc_Dialog", "0"))
        self.list_price_label.setText(_translate("misc_Dialog", "List Price:"))
        self.markup_label_2.setText(_translate("misc_Dialog", "Mark Up"))
        self.tubes_unit_cost_lineEdit.setText(_translate("misc_Dialog", "0"))
        self.shop_bundle_label.setText(_translate("misc_Dialog", "Shop Hours"))
        self.gaskets_label.setText(_translate("misc_Dialog", "Gaskets"))
        self.baffles_label.setText(_translate("misc_Dialog", "Baffles"))

